### ISSUE TITLE
Communication Print vs Connectivity Board

### ISSUE THREAD

**Issue by frankvandenhurk** [miezie/ducoboxopenapi-spec#1]
Could you please indicate whether this is about the Communication Print (old) or Connectivity Board (new)? I have the Communication Print but it looks like this is about the Connectivity Board (that would explain a lot). 

You how state "This document describes the Ethernet interface used on the Duco devices." which could probably be clarified.

**Comment by miezie** [comment]
It is for the new one. From Duco themselves.
